D3.Blog/D3.BlogMvc/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using D3.Blog.Application.Interface;
using D3.Blog.Application.ViewModels;
using D3.Blog.Domain.Core.Notifications;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace D3.BlogMvc.Controllers
{
    public class CustomerController : Controller
    {
        private readonly DomainNotificationHandler _notifications;
        private readonly ICustomerService _customerAppService;

        public CustomerController (
            ICustomerService customerAppService,
            INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
            _customerAppService = customerAppService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            return View(_customerAppService.GetAll());
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CustomerViewModel customerViewModel)
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            if (!ModelState.IsValid) return View(customerViewModel);
            _customerAppService.Add(customerViewModel);

            if (IsValidOperation())
                ViewBag.Sucesso = "Customer Registered!";

            return View(customerViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            if (id == null)
            {
                return NotFound();
            }
            var customerViewModel = await _customerAppService.GetById(id.Value);
            if (customerViewModel == null)
            {
                return NotFound();
            }
            return View(customerViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CustomerViewModel customerViewModel)
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            if (!ModelState.IsValid) return View(customerViewModel);

            _customerAppService.Update(customerViewModel);

            if (IsValidOperation())
                ViewBag.Sucesso = "Customer Updated!";

            return View(customerViewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            if (id == null)
            {
                return NotFound();
            }
            var customerViewModel = await _customerAppService.GetById(id.Value);

            if (customerViewModel == null)
            {
                return NotFound();
            }

            return View(customerViewModel);
        }
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            _customerAppService.Remove(id);
            var customerViewModel = await _customerAppService.GetById(id);
            if (!IsValidOperation())
            {
                return View(customerViewModel);
            }

            ViewBag.Sucesso = "Customer Removed!";
            return RedirectToAction("Index");
        }



        public bool IsValidOperation()
        {
            return (!_notifications.HasNotifications());
        }
    }
}

D3.Blog/D3.BlogMvc/ViewComponents/SummaryViewComponent.cs
using System.Threading.Tasks;
using D3.Blog.Domain.Core.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace D3.BlogMvc.ViewComponents
{
    public class SummaryViewComponent: ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;
        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult((_notifications.GetNotifications()));//获取领域通知的结果
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));//传给ModelState，一般展示操作结果信息

            return View();
        }
    }
}

D3.Blog/D3.BlogMvc/Views/Customer/Create.cshtml
@model D3.Blog.Application.ViewModels.CustomerViewModel
@{
    Layout = null;
    ViewData["Title"] = "Register new Customer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="~/css/vender.css" />
        <link rel="stylesheet" asp-href-include="~/css/index.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="~/css/all.min.css" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- import CSS -->
    <link rel="stylesheet" href="~/elementUI/index.css">
</head>
<body>
    <h2>@ViewData["Title"]</h2>

    <form asp-action="Create">
        <div class="form-horizontal">
            <hr />

            @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
            <vc:summary />

            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="BirthDate" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-action="Index" class="btn btn-info">Back to List</a>
                </div>
            </div>
        </div>
    </form>
    <environment names="Development">
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
    </environment>
    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.15.2/axios.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script src="~/js/vendor.js"></script>
        <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/axios/axios.min.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script type="text/javascript" asp-src-include="~/js/all.min.js"></script>
        <script src="~/elementUI/index.js"></script>
    </environment>
</body>
</html>

D3.Blog/D3.BlogMvc/Views/Customer/Delete.cshtml
@model D3.Blog.Application.ViewModels.CustomerViewModel
@{
    Layout = null;
    ViewData["Title"] = "Edit Customer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="~/css/vender.css" />
        <link rel="stylesheet" asp-href-include="~/css/index.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="~/css/all.min.css" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- import CSS -->
    <link rel="stylesheet" href="~/elementUI/index.css">
</head>
<body>
<h2>@ViewData["Title"]</h2>

<form asp-action="Delete">
    <vc:summary />

    <h3>Are you sure you want to delete the @Model.Name?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BirthDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BirthDate)
            </dd>
        </dl>


        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>
    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.15.2/axios.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script src="~/js/vendor.js"></script>
        <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/axios/axios.min.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script type="text/javascript" asp-src-include="~/js/all.min.js"></script>
        <script src="~/elementUI/index.js"></script>
    </environment>
</body>
</html>

D3.Blog/D3.BlogMvc/Views/Customer/Edit.cshtml
@model D3.Blog.Application.ViewModels.CustomerViewModel
@{
    Layout = null;
    ViewData["Title"] = "Edit Customer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="~/css/vender.css" />
        <link rel="stylesheet" asp-href-include="~/css/index.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="~/css/all.min.css" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- import CSS -->
    <link rel="stylesheet" href="~/elementUI/index.css">
</head>
<body>
    <h2>@ViewData["Title"]</h2>

    <form asp-action="Edit">
        <div class="form-horizontal">
            <hr />

            <input type="hidden" asp-for="Id" />

            @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
            <vc:summary />

            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="BirthDate" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <a asp-action="Index" class="btn btn-info">Back to List</a>
                </div>
            </div>
        </div>
    </form>
    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.15.2/axios.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script src="~/js/vendor.js"></script>
        <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/axios/axios.min.js"></script>
        <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
        <script type="text/javascript" asp-src-include="~/js/all.min.js"></script>
        <script src="~/elementUI/index.js"></script>
    </environment>
</body>
</html>

D3.Blog/D3.BlogMvc/Views/Customer/Index.cshtml
@model IEnumerable<D3.Blog.Application.ViewModels.CustomerViewModel>
@{
    ViewData["Title"] = "Customer Management";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="~/css/vender.css" />
        <link rel="stylesheet" asp-href-include="~/css/index.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="~/css/all.min.css" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- import CSS -->
    <link rel="stylesheet" href="~/elementUI/index.css">
</head>
<body>


<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="glyphicon glyphicon-plus-sign"></span> Register New
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDate)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil">编辑</span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search">详细</span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash">删除</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade" id="customerHistory" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Customer Data History</h4>
            </div>
            <div class="modal-body">
                <p id="customerHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<environment include="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.15.2/axios.js"></script>
    <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
    <script src="~/js/vendor.js"></script>
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/js/axios/axios.min.js"></script>
    <script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
    <script type="text/javascript" asp-src-include="~/js/all.min.js"></script>
    <script src="~/elementUI/index.js"></script>
</environment>
</body>
</html>