D3.Blog/D3.BlogMvc/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System.Threading.Tasks;
using Autofac.Extensions.DependencyInjection;
using D3.Blog.Application.Interface;
using D3.Blog.Application.ViewModels;
using D3.Blog.Application.ViewModels.Article;
using D3.Blog.Application.ViewModels.PostGroup;
using D3.Blog.Domain.Core.Notifications;
using D3.Blog.Domain.Enums;
using D3.Blog.Domain.Infrastructure;
using D3.BlogMvc.Models;
using D3.BlogMvc.Models.AccountModels;
using D3.BlogMvc.Models.PostModels;
using Infrastructure.Logging;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;
using Infrastructure.Data.Database;
using Infrastructure.Identity.Models;
using Infrastructure.NLoger;
using Remotion.Linq.Parsing.Structure.IntermediateModel;

namespace D3.BlogMvc.Controllers
{
    /// <summary>
    /// 文章控制器
    /// </summary>
    [Authorize]
    public class PostController : BaseController
    {

        private readonly IArticleService _articleService;

        private readonly IPostGroupServer _postGroupServer;

        private IUser _user;

        /// <summary>
        /// 构造函数注入
        /// </summary>
        /// <param name="articleService"></param>
        /// <param name="postGroupServer"></param>
        /// <param name="userManager"></param>
        /// <param name="roleManager"></param>
        /// <param name="signInManager"></param>
        /// <param name="_logger"></param>
        /// <param name="notifications"></param>
        public PostController(
            IArticleService articleService,
            IPostGroupServer postGroupServer,
            UserManager<AppBlogUser> userManager,
            RoleManager<AppBlogRole> roleManager,
            SignInManager<AppBlogUser> signInManager,
            INotificationHandler<DomainNotification> notifications,
            IUser user, ICustomerLogging _logger)
            : base(userManager, roleManager, signInManager, notifications, _logger)
        {
            _articleService = articleService;
            _postGroupServer = postGroupServer;
            _user = user;
        }

        /// <summary>
        /// 写文章页面 富文本编辑器
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult WritePost()
        {
            ViewBag.title = "YBLOG-写文章";
            ViewBag.editorType = 1;//富文本编辑器
            ViewBag.container = "container-fluid";//写文章页面和其他页面的样式控制
                                                  //读取个人系列
            var model = LoadUserGroup();
            return View(model);
        }

        /// <summary>
        /// 保存文章
        /// </summary>
        /// <param name="articleModel"></param>
        /// <param name="flag">1:发布，2:保存，其余默认保存</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public JsonResult WritePost([FromForm]NewArticleModel articleModel, [FromQuery]string flag = "1")
        {
            var a = _articleService.GetByFilter(x => x.Title.Equals(articleModel.Title));
            if (a != null)
            {
                return new JsonResult("文章标题已存在，请重新输入");
            }

            NewArticleModel mo = articleModel;
            mo.CreateTime = DateTime.Now;
            switch (flag)
            {
                case "3":
                    //发布，状态变审核中
                    mo.Status = ArticleStatus.Verify;
                    break;
                case "1":
                    //只保存，不进入审核
                    mo.Status = ArticleStatus.Savedraft;
                    break;
                default:
                    mo.Status = ArticleStatus.Verify;
                    break;
            }
            if (articleModel.BlogType == ArticleSource.Original)
            {
                if (_user != null)
                {
                    mo.Author = _user.Name;
                }
            }
            _articleService.Add(mo);
            var error = _notifications.GetNotifications().Select(n => n.Value);//通知结果
            return new JsonResult(error);
        }


        /// <summary>
        /// 写文章页面，markdown编辑器
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult MarkDownEditor()
        {
            ViewBag.title = "YBLOG-写文章";
            ViewBag.editorType = 2;//富文本编辑器
            ViewBag.container = "container-fluid";//写文章页面和其他页面的样式控制
            var model = LoadUserGroup();
            return View(model);
        }

        /// <summary>
        /// 文章详细页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> PostDetails([FromRoute]string id)
        {
            ViewBag.queryValue = id;
            var model = await _articleService.GetById(int.Parse(id));
            if (model == null)
            {
                return new StatusCodeResult((int)HttpStatusCode.NotFound);
            }
            else
            {
                Tuple<LoginModel, RegisterModel, ArticleViewModel> tmodel = new Tuple<LoginModel, RegisterModel, ArticleViewModel>(new LoginModel(), new RegisterModel(), model);
                return View(tmodel);
            }

        }

        /// <summary>
        /// 个人文章管理
        /// </summary>
        /// <param name="flag">1:全部 2:已发布 3:审核中 4:草稿箱 5:回收站</param>
        /// <param name="pageindex"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult ArticleManager([FromQuery]string flag = "1", [FromQuery]int pageindex = 1)
        {
            int pagesize = 10;//页大小
            ViewBag.container = "container";//写文章页面和其他页面的样式控制
            ViewBag.Title = "文章管理";
            ViewBag.flag = flag;
            ViewBag.pageindex = pageindex;
            IEnumerable<ArticleViewModel> result = new List<ArticleViewModel>();
            if (_user != null)
            {
                var uid = -1;
                if (_user.Id != null)
                {
                    uid = int.Parse(_user.Id);
                }
                switch (flag)
                {
                    case "1":
                        result = _articleService.GetList<DateTime>(x => x.AddUserId == uid, x => x.AddTime);//全部
                        break;
                    case "2":
                        result = _articleService.GetList<DateTime>(x => x.AddUserId == uid && x.IsPublish == true, x => x.AddTime);//已发布
                        break;
                    case "3":
                        result = _articleService.GetList<DateTime>(x => x.AddUserId == uid && x.Status == ArticleStatus.Verify, x => x.AddTime);//审核中
                        break;
                    case "4":
                        result = _articleService.GetList<DateTime>(x => x.AddUserId == uid && x.Status == ArticleStatus.Savedraft, x => x.AddTime);//草稿箱
                        break;
                    case "5":
                        result = _articleService.GetList<DateTime>(x => x.AddUserId == uid && x.Status == ArticleStatus.Deleted, x => x.AddTime);//回收箱
                        break;
                }
                ViewBag.totalCount = result.Count();
            }
            result = result.Skip((pageindex - 1) * pagesize).Take(pagesize).ToList();


            return View(result);
        }


        /// <summary>
        /// 个人分类管理
        /// </summary>
        /// <param name="isSuccess"></param>
        /// <param name="pageindex"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult UserClassify()
        {
            ViewBag.Title = "个人分类管理";
            var postgroup = new List<ShowPostGroupViewModel>();
            var result = _postGroupServer.GetList<int>(x => x.OwinUserId == int.Parse(_user.Id));
            if (result != null)
            {
                postgroup = result.ToList();
            }
            return View(postgroup);
        }

        /// <summary>
        /// 个人分组管理
        /// </summary>
        /// <param name="isSuccess"></param>
        /// <param name="pageindex"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult UserGroup()
        {
            ViewBag.Title = "个人分组管理";
            var postgroup = new List<ShowPostGroupViewModel>();
            var result = _postGroupServer.GetList<int>(x => x.OwinUserId == int.Parse(_user.Id));
            if (result != null)
            {
                postgroup = result.ToList();
            }
            return View(postgroup);
        }


        public bool IsValidOperation()
        {
            return (!_notifications.HasNotifications());
        }


        
        [HttpGet]
        public IActionResult GetData()
        {
            var postgroup = new List<ShowPostGroupViewModel>();
            var result = _postGroupServer.GetList<int>(x => x.OwinUserId == int.Parse(_user.Id));
            if (result != null)
            {
                postgroup = result.ToList();
            }
            return Json(new {total=postgroup.Count,rows =postgroup});
        }



        /// <summary>
        /// 删除个人分组
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public JsonResult DeleteGroup(int id)
        {
             _postGroupServer.Remove(id);
             var error = _notifications.GetNotifications().Select(n => n.Value);//通知结果
             return new JsonResult(error);
        }



        /// <summary>
        /// 读取个人分组
        /// </summary>
        /// <returns></returns>

D3.Blog/D3.BlogMvc/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using D3.Blog.Application.Interface;
using D3.Blog.Application.ViewModels.PostGroup;
using D3.Blog.Domain.Core.Notifications;
using D3.Blog.Domain.Infrastructure;
using Infrastructure.Identity.Models;
using Infrastructure.NLoger;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace D3.BlogMvc.Controllers
{
    /// <summary>
    /// 用户操作控制器
    /// </summary>
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IArticleService _articleService;
        
        private readonly IPostGroupServer _postGroupServer;

        private IUser _user;


        public UserController(
            IArticleService articleService,
            IPostGroupServer postGroupServer,
            UserManager<AppBlogUser> userManager, 
            RoleManager<AppBlogRole> roleManager, 
            SignInManager<AppBlogUser> signInManager,
            INotificationHandler<DomainNotification> notifications,
            IUser user,ICustomerLogging _logger)
            : base(userManager, roleManager, signInManager, notifications,_logger)
        {
            _articleService = articleService;
            _postGroupServer = postGroupServer;
            _user = user;
        }

        /// <summary>
        /// 添加用户分组
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddUserGrout(string groupName)
        {
            PostGroupViewModel model=new PostGroupViewModel(groupName,int.Parse(_user.Id));
            _postGroupServer.Add(model);
            var error = _notifications.GetNotifications().Select(n => n.Value);//通知结果
            var enumerable = error as string[] ?? error.ToArray();
            if (enumerable.Any())
            {
                return new JsonResult(enumerable.FirstOrDefault());
            }
            return new JsonResult("success");
        }
        /// <summary>
        /// 添加用户个人分类
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddUserClassify(string classifyName)
        {
            PostGroupViewModel model = new PostGroupViewModel(classifyName, int.Parse(_user.Id));
            _postGroupServer.Add(model);
            var error = _notifications.GetNotifications().Select(n => n.Value);//通知结果
            var enumerable = error as string[] ?? error.ToArray();
            if (enumerable.Any())
            {
                return new JsonResult(enumerable.FirstOrDefault());
            }
            return new JsonResult("success");
        }


        
    }
}

D3.Blog/D3.BlogMvc/Views/Post/UserClassify.cshtml
@using System.Security.Claims
@using D3.Blog.Domain.Enums
@using Infrastructure.Data.Database
@using Infrastructure.Identity.Models
@using Microsoft.AspNetCore.Identity
@model List<D3.Blog.Application.ViewModels.PostGroup.ShowPostGroupViewModel>
@inject UserManager<AppBlogUser> userManager
@inject SignInManager<AppBlogUser> signInManager
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
    <meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no,viewport-fit=cover">
    <title>YL-Blog-@ViewBag.Title</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/css/home/style.css">
    <link rel="stylesheet" href="~/css/posts/write.css">
    <link rel="stylesheet" href="~/fontawesome-free/css/all.css">
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/lib/markdown/css/editormd.min.css" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="~/bootstrap-tokenfield/css/bootstrap-tokenfield.min.css">
    <link rel="stylesheet" href="~/bootstrap-tokenfield/css/tokenfield-typeahead.min.css">
    <link href="~/bootstrap-plus/table/bootstrap-table.min.css" rel="stylesheet" />
    <!--[if lt IE 9]><script src="~/lib/html5.min.js"></script><![endif]-->
    <style>
        * {
            font-family: "Arial","Microsoft YaHei","黑体","宋体",sans-serif;
        }
        #quick-search > ul, li {
            padding: 0;
            margin: 0;
        }

        #quick-search ul {
            display: flex;
            line-height: 30px;
            padding: 0 10px;
            margin: 5px 5px;
        }

        #quick-search ul li {
            list-style: none;
            margin-right: 20px;
            border-bottom: 2px solid white;
        }

        #quick-search ul .active {
            border-bottom: 2px solid #309dda;
        }

        #quick-search ul li:hover {
            border-bottom: 2px solid #309dda;
            cursor: pointer;
        }

        #blogtype1:before {
            content: '';
            display: block;
            left: -4px;
            top: 6px;
            width: 8px;
            height: 8px;
            position: absolute;
            transform: rotate(45deg);
            background-color: #5bea37;
        }

        #blogtype2:before {
            content: '';
            display: block;
            left: -4px;
            top: 6px;
            width: 8px;
            height: 8px;
            position: absolute;
            transform: rotate(45deg);
            background-color: #3ba8f5;
        }

        #blogtype3:before {
            content: '';
            display: block;
            left: -4px;
            top: 6px;
            width: 8px;
            height: 8px;
            position: absolute;
            transform: rotate(45deg);
            background-color: #f9cd2f;
        }

        .info {
            margin-left: 30px;
        }
        .pagination-detail {
            display: none;
        }
        .bootstrap-table .fixed-table-container .table th, .bootstrap-table .fixed-table-container .table td {
            vertical-align: middle;
            box-sizing: border-box;
            padding: 3px;
        }
    </style>
</head>
<body>
    <div id="app">
        @await Html.PartialAsync("_sidebarMenu")@*侧边导航*@
        <div class="wrapper">
            <!-- Page Content  -->
            <div id="content">
                @await Html.PartialAsync("_TopNavbarMenu")@*顶部导航*@
                <div data-flag="1" id="search-posts">
                    <form data-flag="1" asp-controller="Home" asp-action="Search" method="post">
                        <input data-flag="1" type="text" placeholder="请输入搜索内容" name="searchtext" id="searchtext" style="line-height: 30px;width: 400px;border: 1px solid lightblue;padding-left:10px" />
                        <button data-flag="1" type="submit" style="line-height: 30px;border: none;background-color: #309dda;width: 60px;border: 1px solid #309dda;">搜索</button>
                    </form>
                </div>
                <div class="container" style="display: flex; padding: 0 25px;height:760px">
                    <div id="aside-content">
                        <ul>
                            <li class="write-aside"><a href="#">富文本编辑器</a></li>
                            <li class="write-aside"><a asp-controller="Post" asp-action="MarkDownEditor">MarkDown编辑器</a></li>
                        </ul>
                        <hr />
                        <ul>
                            <li class="write-aside"><a asp-controller="Post" asp-action="ArticleManager" asp-route-flag="1">文章管理</a></li>
                            <li class="write-aside checked"><a asp-controller="Post" asp-action="UserClassify">个人分类管理</a></li>
                            <li class="write-aside"><a asp-controller="Post" asp-action="UserGroup">个人分组管理</a></li>
                            <li class="write-aside"><a href="#">评论管理</a></li>
                        </ul>
                    </div>
                    <!--文章管理List-->
                    <div id="write-area">
                        @* <div style="margin: 5px 0px 10px; padding: 0 5px; line-height: 60px; background-color: #F2F5F7;">搜索</div> *@
                        <div id="toolbar">
                            <div>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">新增</button>
                            </div>
                        </div>
                        <table id="groupTab"></table>
                    </div><!--end 文章管理List-->
                </div>

                <!--页脚-->
                <footer class="footer">
                    <div class="footer-header">
                        <p>
                            <span>Copyright</span><span>&copy;</span><span>2018&nbsp;&nbsp;</span><a href="#">阿里布布</a><span>
                                &nbsp;&nbsp;Design By
                                zyl
                            </span>
                    </div>
                </footer>

                <!--弹窗-->
                <!-- Modal -->
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">新增文章分组</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form id="groupform" asp-controller="User" asp-action="AddUserClassify" onkeydown="if(event.keyCode==13){return false;}">
                                    <input type="text" name="classifyName" class="form-control" id="classifyName" placeholder="分类名称">
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                                        <button type="button" class="btn btn-primary" v-on:click="Save(2,$event)">保存</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>


        <!--附带效果html-->
        <div class="overlay"></div><!--侧边菜单覆盖物-->
        <div class="tooltip bs-tooltip-top scroll-to-top" data-placement="left" data-toggle="tooltip" title="回到顶部">
            <!--回到顶部-->
            <i class="far fa-arrow-alt-circle-up fa-2x"></i>
        </div>
        <div class="tooltip bs-tooltip-top feedback" data-placement="left" data-toggle="tooltip" title="建议反馈">
            <!--问题反馈和回到顶部-->
            <i class="far fa-envelope fa-2x"></i>
        </div>
    </div>
    <script src="~/js/vue/polyfill.min.js"></script>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="~/js/jquery/jquery-3.3.1.min.js"></script>
    <!-- Popper.JS -->
    <script src="~/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!--bootstrap 下拉框-->
    <script src="~/js/bootstrap/bootstrap-select.min.js"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="~/js/jquery/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/axios/axios.min.js"></script>
    <!--tag 输入框-->
    <script src="~/bootstrap-tokenfield/bootstrap-tokenfield.min.js"></script>
    <script src="~/bootstrap-plus/table/bootstrap-table.min.js"></script>
    <script src="~/bootstrap-plus/table/bootstrap-table-zh-CN.min.js"></script>
    <script src="~/js/vue/vue.js"></script>
    <script src="~/js/holder/holder.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
<script src="~/js/posts/manager.js"></script>
<script>
    $(function() {
        $('#groupTab').bootstrapTable({
            url: "/Post/GetData",
            toolbar: '#toolbar',
            pageSize: 15,
            pageNumber: 1,
            showToggle: true,
            showRefresh: true,
            showColumns: true,
            search: true,
            pagination: true,
            columns: [
                {
                    field: "id",
                    title: '序号'
                }, {
                    field: 'groupName',
                    title: '分组名称'
                }, {
                    field: 'owinUser',
                    title: '操作',
                    width:'120',
                    formatter: function operateFormatter(value, row, index) {
                        return [
                            '<div class="btn-group btn-group-sm" role="group" aria-label="...">',
                            '<button type="button" class="btn btn-secondary">修改</button>&nbsp;&nbsp;',
                            '<button type="button" class="btn btn-warning">删除</button>',
                            '</div>'
                        ].join('');
                    } //自定义方法，添加操作按钮
                }
            ]
        });
    });

</script>
</body>
</html>